### ISSUE TITLE
Cleanup current form module

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#112]
- [ ] we don't need `compact` modificator anymore, that's the wrong concept
- [ ] `fieldset` and `legend` should be elements
- [ ] which means we don't need form module at all 😉

**Comment by kruchy8** [comment]
When updating form module, please have in mind that we shouldn't use internal variables from other components. Please replace `$button-height` and `$button-icon-border-width` variables.
