### ISSUE TITLE
Create component for icons

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#119]
All icons should folow same rules:
- 20 x 20 px - icon size
- 24 x 24 px - icon with padding size
- 48 x 48 px - overal size (12px of padding)

We will follow Material design rules: https://material.io/guidelines/style/icons.html#icons-system-icons

![image](https://user-images.githubusercontent.com/5119280/32002551-15d6a934-b99d-11e7-90a8-475918e821b2.png)

> Icon content is limited to the 20dp x 20dp live area, with 4dp of padding around the perimeter.

![image](https://user-images.githubusercontent.com/5119280/32002526-0572eb70-b99d-11e7-92e5-07d9e21688df.png)
> Clearance area
> 
> Icon: 24dp
> Touch target: 48dp

**Comment by anqaka** [comment]
waiting for new design, merged in develop
