### ISSUE TITLE
Component for header marketing messeges

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#122]
Check if we should make this part of the header a separate component
![image](https://user-images.githubusercontent.com/5119280/32051382-a8aefbfa-ba54-11e7-9b55-4fa0192ef3f9.png)

**Comment by szafran89** [comment]
In new design we don't have these marketing messages https://app.zeplin.io/project/59d7824828a80b524cc9de18/screen/5a0aadf86b7d704d4b2c0601

@Igloczek should we close this issue or we're gonna add these elements to header in future?

**Comment by Igloczek** [comment]
We will need it on the product page, but for now, we can close it, b/c it exist just in one place.
