### ISSUE TITLE
Use predefined spacer variable to keep consistency in margins and paddings

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#130]
Proposal:
```scss
$spacer: 8px !default;
$spacer--large: 16px !default;
```

**Comment by Januszpl** [comment]
Maybe $spacer--double  $spacer--triple ? (8px / 16px / 24px) ? or --large  /--extra-large

**Comment by szafran89** [comment]
I'll handle it

**Comment by szafran89** [comment]
Added new variables and removed existing $margin-base/$padding-base  https://github.com/SnowdogApps/magento2-alpaca-components/commit/bbef5db2779faabb8800e5d7d20c90df89695784
```
// Spacers
$spacer                : 8px !default;
$spacer--medium        : 16px !default;
$spacer--large         : 32px !default;
$spacer--extra-large   : 48px !default;
