### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by anqaka** [SnowdogApps/magento2-alpaca-components#133]
Please note here all issue concerning a11y. 
If you have the component to check, smth needs to have special keyboard support or you've finish some component and have doubts if a11y is implemented. 
#106

**Comment by anqaka** [comment]
Form fields a11y:
- select field (with custom layout by js) is not accessible - TO DO
- file upload field  is not fully accessible - to improve
- radio button - automatically check using keyboard - to check/imprive

**Comment by szafran89** [comment]
<img width="672" alt="screenshot at lis 07 12-05-34" src="https://user-images.githubusercontent.com/5370251/32490602-ff2b629e-c3b3-11e7-984c-45813eb7dec6.png">

**Comment by anqaka** [comment]
I'm closing this issue, from now, please create new issue for every a11y related problem, component, element... and add a11y label
