### ISSUE TITLE
Update newsletter design

### ISSUE THREAD

**Issue by Januszpl** [SnowdogApps/magento2-alpaca-components#134]
Refs: #124 

update design to match module (after #124 will be merged).

Some comments on zeplin:
mobile
https://app.zeplin.io/project/59d7824828a80b524cc9de18/screen/59e77331380b7f748506c1bf
tablet:
https://app.zeplin.io/project/59d7824828a80b524cc9de18/screen/59ef2c778e9c8a5b21a672d5
desktop:
https://app.zeplin.io/project/59d7824828a80b524cc9de18/screen/59d79a442b369915cde2f261

For keeping consistency in the design:

I made by default for every design input without border
opacity for label text - 0.7
opacity for placeholder - 0.7

So we should update in design this and margins/spacing/paddings as well for 8px/16px

**Comment by Igloczek** [comment]
Design updated, all spacers are now 8px or multiplied value. Inputs, buttons, and checkboxes look the same on every device.

**Comment by anqaka** [comment]
Updates implemented in #124
