### ISSUE TITLE
Update links styles

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#138]
According to design, links should have a "fancy" hover effect
![clipboard - 30 pazdziernika 2017 13-30](https://user-images.githubusercontent.com/5119280/32171026-440ff5d4-bd77-11e7-84c3-b6d18adc71d6.png)

**Comment by kjugi** [comment]
Checked our project as for now it's in this places:

+ Footer links - we can see it in every view in zeplin
+ Dropdown menu - when hovering on the main category it has this effect too
+ Pager element - on currently active page i.e. 'catalog' and think on hover in other sites it also occurs
+ Swatcher with size - On catalog page when hover on one product and choosing size of product.
+ More link in homepage banners

In other cases, I think here we have a normal link with green 1px underline or some other standard hover effect.
