### ISSUE TITLE
Menu trigger element refactoring

### ISSUE THREAD

**Issue by szafran89** [SnowdogApps/magento2-alpaca-components#181]
There is added via js `side-menu-trigger__icon--hide` class for element without `side-menu-trigger__icon` class

**Comment by Januszpl** [comment]
js-hide would be useful (with display: none). I wouldn't add js-active/js-show etc. as it can be different   so (js-hide, js-hide-visually)

**Comment by szafran89** [comment]
`Menu trigger` module is removed so I think I can close this issue.
