### ISSUE TITLE
A11y - file upload field

### ISSUE THREAD

**Issue by anqaka** [SnowdogApps/magento2-alpaca-components#193]
file upload field is not fully accessible

- test a11y
- improve a11y implementation

**Comment by Januszpl** [comment]
internal: dev-36913

**Comment by Januszpl** [comment]
@anqaka please check.. I found only some other things to improve #272 related to file upload.

**Comment by anqaka** [comment]
@Januszpl I added some a11y features to this component. Please review MR :)
