### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by szafran89** [SnowdogApps/magento2-alpaca-components#208]
IMO we should change color of the link. Mostly on the design we use `$gray-dark` color instead of `$green`. Additionally it would be great to add modifier `invert`.

My suggestion below:

```
.link { 
  color: $gray-dark;
  &:hover {
    color: $color-primar;
  }
  &--invert {
    color: $color-primar;
    &:hover {
      color: $gray-dark;
    }
  }
}
```

Path to file: https://github.com/SnowdogApps/magento2-alpaca-components/blob/master/components/01-globals/typography/link/_link.scss

**Comment by Januszpl** [comment]
imho Designer when adding/modyfing links should have list of all links variation and we should put in here. I guess this change can result in changes in many elements/modules.

**Comment by kjugi** [comment]
I've done it but not like you mentioned in the code example.

New modifier to link element existing but with different colours. I mean it's gray-dark and color-primary on hover in new modifier `invert`. I don't change the default link styles b/c I don't think it's necessary. If you think it is, please let me know
