### ISSUE TITLE
Add mix-blend-mode to product photos

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#214]
On design, product photos have a grayish background, but in sample data, all photos are using the white background.

We need to add to the styles this line to get the same effect, without changing all images:
```
mix-blend-mode: multiply;
```

As part of this task will be nice to get some photos from Magento and add here, to use exactly same iamges.

**Comment by Januszpl** [comment]
@Igloczek even if now in some places we have white background? (Because than it won't be white anymore) and I was thinking about adding  `$image--blend-mode-multiply` class to `@image` or you think better to go with "per module/view" usage ?

**Comment by Igloczek** [comment]
I'll keep the module/view scope, at all it's mostly related to our design, not a thing that everyone wants to use.
