### ISSUE TITLE
Accessibility utilities

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#221]
Will be nice to have global components for accessibility utilities like visually hidden, to avoid code duplication

Example implementation: https://github.com/SnowdogApps/magento2-alpaca-components/blob/6daddae917ca52eb59d014882672ac2737378362/components/01-globals/typography/label/_label.scss#L23-L33

CC @anqaka

**Comment by Januszpl** [comment]
You  mean global classes like "is-visually-hidden" or "state-visually-hidden" ?
