### ISSUE TITLE
Popup.js fixes

### ISSUE THREAD

**Issue by szafran89** [SnowdogApps/magento2-alpaca-components#244]
Popup.js does not support more than 1 popup per page.

**Comment by Januszpl** [comment]
internal ticket: dev-36695

**Comment by Januszpl** [comment]
@szafran89 can you add more data what effect we should achieve? As it's possible to add another button to show dialog with another content.

**Comment by szafran89** [comment]
No. I mean if I have e.g. `home page` and there are `mini cart popup` and `account popup` called there is error in console or no error but it doesn't work at all. I don't remember exactly how it was.

**Comment by szafran89** [comment]
Can you fix it?
