### ISSUE TITLE
Dropdown list calculates content height the wrong way.

### ISSUE THREAD

**Issue by kruchy8** [SnowdogApps/magento2-alpaca-components#250]
If one put a vertically aligned, margin-separated content, the list would not expand to right height.
![image](https://user-images.githubusercontent.com/12099511/33370541-20b0b6c6-d4f8-11e7-96f4-76f3babfb5ea.png)
**Why it happens:** 
In file `components/02-elements/dropdown-list/dropdown-list.js` on line 60, the content height is calculated using `clientHeight` property. 
This function ignores content margin : (from: https://www.w3schools.com/jsref/prop_element_clientheight.asp) 
`The clientHeight property returns the viewable height of an element in pixels, including padding, but not the border, scrollbar or margin.`
**Possible solution**
Changing line 60 from :
``dropdownContent.style.height = `${setListHeight(dropdownContent)}px``
to: 
`dropdownContent.style.height = 'auto'`;
(and removing function that becomes unnecessary in this case, of course)
Result:
![image](https://user-images.githubusercontent.com/12099511/33370688-97eb41ac-d4f8-11e7-8b3e-7bb10cd78ca8.png)

**Comment by anqaka** [comment]
@kruchy8 it's good idea to fix it, but when we use height: auto, transition doesn't work. :/  Do you have some idea how to improve this code?
and for margin problem: if you could use padding instead of margin? Or it's not a case?
