### ISSUE TITLE
Dropdown-list imporvements

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-alpaca-components#291]
It will be nice to update loading scripts in the last of dropdown importing on page. If we have more than 1 it will not work. Just add in `dropdown-list.hbs` and `dropdown-list--with-nested.hbs`

```
{{#if script }}
    <script src="{{ static 'dropdown-list.js' }}"></script>
{{/if}}
```

And update in this place when it's needed

**Comment by bartdominiak** [comment]
Yes. Tab component also needs this hack.

**Comment by bartdominiak** [comment]
internal: dev-37439
