### ISSUE TITLE
incorrect cursor height on safari in all inputs

### ISSUE THREAD

**Issue by bartdominiak** [SnowdogApps/magento2-alpaca-components#426]
<img width="798" alt="zrzut ekranu 2018-10-3 o 17 35 34" src="https://user-images.githubusercontent.com/18058305/46421642-d3c51180-c732-11e8-82b7-e70f41815080.png">

IMO `line-height` should be `normal` for all inputs.

**Comment by Aekal** [comment]
It looks good now
<img width="645" alt="Zrzut ekranu 2019-04-1 o 16 38 55" src="https://user-images.githubusercontent.com/7126345/55336319-07dc7d80-549d-11e9-9147-cfa91b042eb8.png">
