### ISSUE TITLE
cookie-message is hardly visibile

### ISSUE THREAD

**Issue by koralgolek** [SnowdogApps/magento2-alpaca-components#480]
cookie-message is hardly visibile because it is sticked into the bottom of the site.
Maybe this two css in .cookie-message class will be good idea?

position: fixed;
bottom: 0px;

**Comment by Igloczek** [comment]
Thank for the issue, but we are not planning to make it more visible, you can easily overwrite those styles in your project.
For example, wrap the whole component in a new element to provide necessary layout directives, without touching component itself.
