### ISSUE TITLE
Standard menu - add

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-alpaca-components#67]
Create menu **but** not `dropdown-menu` or `side-menu`. Just menu from mobile devices to desktop device. In one module.

Menu will contains:
+ Main links with dropdown
+ Subcategories with links
+ Commercial/Image in menu with button (not mobile)

We have design how it looks like:
+ [Desktop view with expanded dropdown menu](https://zpl.io/VQ05PGW)
+ [Tablet view with main categories](https://zpl.io/2ykZZ79)
+ [Tablet view with subcategories](https://zpl.io/2jZJJlO)
+ [Mobile view with main cat.](https://zpl.io/VkD6438)
+ [Mobiel view with subcat.](https://zpl.io/adxJdjp)

On mobile/tablet view when we will click on main category it will swipe from left to right with subcategories. That's the main idea

**Comment by Igloczek** [comment]
It's not necessary to keep this as one component, b/c it just adds more complexity.
