### ISSUE TITLE
Product views - update

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-alpaca-components#77]
Push some product views with multiple variants. 

Product view must contain: 
+ Product gallery
+ Product name
+ SKU
+ Reviews
+ Product desc
+ Stock available product
+ Price
+ Product variants, qty etc.
+ Add to wishlist icon
+ Product icons with details
+ Tabs with product content (more info, shipping and returns...)
+ Slider with you make also like
+ Slider with related products

Variants: 
+ Simple product
+ Bundle product
+ Configurable product

Design/projects:
+ [Product desktop](https://zpl.io/2Z0NNkw)
+ [Product desktop - more into tab](https://zpl.io/adxJdqp)
+ [Product dekstop - reviews tab](https://zpl.io/bz8ZQG8)
+ [Product tablet](https://zpl.io/adxJ5wl)
+ [Product mobile](https://zpl.io/a3XB4yy)

**Comment by Januszpl** [comment]
@kjugi as you probably know there is more than 3 types of product - http://docs.magento.com/m2/ee/user_guide/catalog/product-types.html but I think we would need to check usage of what we have in magento before creating any new variant
