### ISSUE TITLE
Icons - globals update

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-alpaca-components#80]
Compare our icons with project... It doesn't look so good and we must update it. Search in project files to icons, download them and replace with existing one. Unfortunately, we don't have one view with all icons. 

Think we are using this icons: https://material.io/icons/. Our graph dsgnr said about it.

[Link to project](https://zpl.io/a7w0e98)

**Comment by kruchy8** [comment]
feature/34770
