### ISSUE TITLE
Button - element update

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-alpaca-components#87]
Update element with the design. Our button is now rounder and green. Icons are without border and hover to green colour from [variables](https://github.com/SnowdogApps/magento2-alpaca-components/issues/84)

Project files:
+ [homepage buttons](https://zpl.io/VQ051x9)
+ [catalog list buttons](https://zpl.io/aRMpnjr)

**Comment by kruchy8** [comment]
branch feature/35006
